name: Run build KMP for MacOS

on:
    workflow_dispatch:
    workflow_call:

defaults:
    run:
        shell: bash

permissions:
    contents: read

env:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    build-linux:
        name: Run build on ${{ matrix.os }}

        continue-on-error: false
        strategy:
            fail-fast: true
            matrix:
                os: [ 'ubuntu-latest' ]

        runs-on: ${{ matrix.os }}
        timeout-minutes: 15

        concurrency:
            group: run-build-macos-${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
            cancel-in-progress: true

        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            -   name: Setup environment
                uses: ./.github/actions/setup
                with:
                    cache-read-only: ${{ github.ref != 'refs/heads/main' }}

            -   name: Run check
                continue-on-error: false
                run: |
                    ./gradlew -Vs detekt checkMacos

            -   name: (Fail-only) Upload reports
                if: failure()
                uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
                with:
                    name: reports-build-macos
                    path: |
                        **/build/reports/**
